# General Settings
title: Phoebe's Notebook
name: Gilead Raab
job_title: Back-end developer
email: gileadraab@gmail.com
description: Figuring out the world, one line of code at a time. Follow me on Twitter or drop me a line.
avatar: https://avatars.githubusercontent.com/u/42283792?v=4
favicon: /static/favicon/favicon.ico
twitter_handler: gileadraab
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Pages
pages:
#- {layout: 'page', url: /about, title: 'About'}


# Social Accounts
social_networks:
-  { name: facebook, url: 'http://facebook.com/gileadraab' }
-  { name: twitter, url: 'http://twitter.com/gileadraab' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'http://github.com/gileadraab/' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 0
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed