date: "28/12/22 23:32"
title: "Automating Flask applications deployments using Ansible, Gunicorn and Nginx"
image: "ansible.png"
tags: 
- "ansible" 
- "automation"
- "deploy"
- "flask"
show_comments: 1
markdown_path: "automating-deployments-with-ansible.md"
slug: "automating-deployments-with-ansible"
draft: false